<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFrameworks>netstandard2.0;net8.0-windows</TargetFrameworks>
        <OutputType>Exe</OutputType>
        <Nullable>enable</Nullable>
        <UseDi>true</UseDi>
    </PropertyGroup>
    
    <ItemGroup>
        <ProjectReference Include="..\..\src\Excel\RxBim.Tools.TableBuilder.Excel\RxBim.Tools.TableBuilder.Excel.csproj"/>
    </ItemGroup>
    
    <ItemGroup>
        <None Include="images\Example.jpg" CopyToOutputDirectory="Always"/>
    </ItemGroup>
</Project>
